# Travis flow
# - specify docker as a dependency
# - build test version of React module
# - run tests
# - build prod version of all module
# - push all to Docker Hub
# - tell Elastic Search to update
sudo: required
language: generic   # fix-me: no Rakefile found
services:
  - docker

before_install:
  - docker build -t kbly/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kbly/react-test npm test

after_success:
  - docker build -t kbly/multi-client ./client -f ./client/Dockerfile.prod
  - docker build -t kbly/multi-nginx ./nginx -f ./nginx/Dockerfile.prod
  - docker build -t kbly/multi-server ./server -f ./server/Dockerfile.prod
  - docker build -t kbly/multi-worker ./worker -f ./worker/Dockerfile.prod
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kbly/multi-client
  - docker push kbly/multi-nginx
  - docker push kbly/multi-server
  - docker push kbly/multi-worker
