version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./rok-deployer/nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./rok-server
    volumes:
      - /app/node_modules
      - ./rok-server:/app
    env_file:
      - ./rok-server/.env
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./rok-client
    volumes:
      - /app/node_modules
      - ./rok-client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./rok-worker
    env_file:
      - ./rok-worker/.env
    volumes:
      - /app/node_modules
      - ./rok-worker:/app
