apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1                             # specify the number of deployment, create 1 pod here
  selector:                               # how Deployment find the pods manage after they created ?
    matchLabels:
      component: redis                    # Deployment will looking for objects with label of component web
  template:                               # define pod template, so Deployment can maintain
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379

