apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1                             # specify the number of deployment, create 1 pod here
  selector:                               # how Deployment find the pods manage after they created ?
    matchLabels:
      component: worker                   # Deployment will looking for objects with label of component web
  template:                               # define pod template, so Deployment can maintain
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: kbly/multi-worker
          env:                            # connect to Redis Cluster IP
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
